### ISSUE TITLE
Предопределяется title

### ISSUE THREAD

**Issue by MihaylovNikitos** [2gis/contesto#65]
У объектов(наследованных от Component) предопределятся title на класс объекта или выдает ошибку. Происходит, примерно где-то тут:
https://github.com/2gis/contesto/blob/master/contesto/basis/__init__.py#L64

Это воспроизводится на многих тестах, где есть title, н-р:
[test_auto_search_repair] 
(https://github.com/2gis/online4/blob/c134a6ba4265a74eb796b7540cb96687b37c63ea/functional-tests/tests/search/route_search/route_search_history.py#L27)

Ошибка:
```
======================================================================
ERROR: test_auto_search_repair_http<colon><slash><slash>staging<dot>online<dot>ostack<dot>test<slash>novosibirsk<slash>routeSearch<slash>routeTab<slash>rsType<slash>car<slash>from<slash>82<dot>888715,55<dot>05427╎заельцовская<slash>to<slash>82<dot>893849,55<dot>078699╎студенческая (search.route_search.route_search_history.TestRouteSearchHistory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/initializer.py", line 18, in wrapper
    result = test(*args, **kwargs)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/dataprovider.py", line 254, in <lambda>
    standalone_func = lambda *args: func(*(args + data_set))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/tests/search/route_search/route_search_history.py", line 42, in test_auto_search_repair
    route_info_duration = self.page.from_to_auto_results.autos_mini[0].duration
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/components/page.py", line 876, in from_to_auto_results
    self.test.find_element_by_css_selector(RouteSearchAutoResults.selectors['self']))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/components/component.py", line 14, in __init__
    super(Component, self).__init__(test, element)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/contesto/basis/component.py", line 17, in __init__
    super(Component, self).__init__(driver)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/contesto/basis/__init__.py", line 64, in __init__
    self.title = self.__class__.__name__
AttributeError: can't set attribute
```

Если у себя переименую title, то тест проходит.

**Comment by nwlunatic** [comment]
https://github.com/2gis/contesto/pull/69
