### ISSUE TITLE
Не ловиться ElementNotFound, когда нет элемента

### ISSUE THREAD

**Issue by MihaylovNikitos** [2gis/contesto#67]
В новой версии, не ловится ElementNotFound, когда нет элемента.
В старой версии(на @53ff11259171a8fca74cbc04bf83bbdec668424d) ловится.
Версия python неважна, Selenium стоит 2.48.0.

Заместо него летит selenium.common.exceptions.NoSuchElementException(что интересно, т.к в Selenium он должен игнорироватся
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/support/wait.py#L50
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/support/wait.py#L74

Н-р воспроизводится тестах:
[test_open_close_gallery](https://github.com/2gis/online4/blob/b9d53ac348fe1839a7b7de1a3f0a926a793bb67a/functional-tests/tests/search/photos.py#L38)
[test_building_name_drilldown_verify](https://github.com/2gis/online4/blob/c134a6ba4265a74eb796b7540cb96687b37c63ea/functional-tests/tests/search/minicards.py#L148)
Их можно легко найти: , none()

Ошибка:
```
======================================================================
ERROR: test_building_name_drilldown_verify_('Красный проспект 71 <slash>', 'building', '<slash>novosibirsk') (search.minicards.TestMiniCard)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/initializer.py", line 18, in wrapper
    result = test(*args, **kwargs)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/lode_runner/plugins/dataprovider.py", line 254, in <lambda>
    standalone_func = lambda *args: func(*(args + data_set))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/tests/search/minicards.py", line 162, in test_building_name_drilldown_verify
    self.page.search_results.select_geo_tab()
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/components/frame/frame.py", line 123, in select_geo_tab
    if self.wizard is not None:
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/util/decorators.py", line 16, in decorated
    return f(self, *args, **kwargs)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/classes/components/frame/frame.py", line 156, in wizard
    return Wizard(self.test, container.find_element_by_css_selector(Wizard.selectors['self']))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 277, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 474, in find_element
    {"using": by, "value": value})['value']
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/contesto/core/driver.py", line 59, in execute
    result = super(Driver, self).execute(driver_command, params)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/errorhandler.py", line 181, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".wizard"}**
  (Session info: chrome=47.0.2522.1)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Linux 3.13.0-63-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10.03 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'uk-rnd-26', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.7.0_79'
*** Element info: {Using=css selector, value=.wizard}
Session ID: 3b53c051ea742175e7b1f064d2f2d740
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.2ufUsX}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2522.1, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
Screenshot: available via screen
Stacktrace:
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable (ErrorHandler.java:206)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed (ErrorHandler.java:158)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:647)
    at org.openqa.selenium.remote.RemoteWebElement.execute (RemoteWebElement.java:326)
    at org.openqa.selenium.remote.RemoteWebElement.findElement (RemoteWebElement.java:197)
    at org.openqa.selenium.remote.RemoteWebElement.findElementByCssSelector (RemoteWebElement.java:286)
    at org.openqa.selenium.By$ByCssSelector.findElement (By.java:430)
    at org.openqa.selenium.remote.RemoteWebElement.findElement (RemoteWebElement.java:193)
    at sun.reflect.GeneratedMethodAccessor19.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:606)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke (EventFiringWebDriver.java:334)
    at com.sun.proxy.$Proxy2.findElement (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.findElement (EventFiringWebDriver.java:405)
    at sun.reflect.GeneratedMethodAccessor19.invoke (None:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:606)
    at org.openqa.selenium.remote.server.KnownElements$1.invoke (KnownElements.java:64)
    at com.sun.proxy.$Proxy3.findElement (None:-1)
    at org.openqa.selenium.remote.server.handler.FindChildElement.call (FindChildElement.java:44)
    at org.openqa.selenium.remote.server.handler.FindChildElement.call (FindChildElement.java:1)
    at java.util.concurrent.FutureTask.run (FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:615)
    at java.lang.Thread.run (Thread.java:745)
```

**Comment by rseek** [comment]
Привет!
По-моему в текущей реализации ElementNotFound можно ловить, только если используешь find_element контестовский, а судя по логу, ты используешь стоковый selenium'овский find_element.
там нету wait, поэтому и не игнорируется NoSuchElementException

**Comment by MihaylovNikitos** [comment]
В том то и проблема, что используем find_element контестовский,т.е юзаем ContestoWebDriver)

**Comment by rseek** [comment]
А где можно код тестов посмотреть?
по ссылкам получаю 404.

Про find_element я подумал вот почему:
```
    return Wizard(self.test, container.find_element_by_css_selector(Wizard  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 474, in find_element.selectors['self']))
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 277, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 474, in find_element
    {"using": by, "value": value})['value']
```
В этом куске stacktrace явно видно, что вызывается find_element из selenium:   ```
File "/home/n.mikhaylov/2gis/online4-for-test/functional-tests/.tox/lib/python3.4/site-packages/selenium/webdriver/remote/webelement.py", line 474, in find_element
```
И он вызывается не из contesto.core.finder.find_element.


То есть драйвер-то вы используете contesto, а find_element используется не контестовский, т.к. его надо явно импортить и использовать. Если хочется использовать его возможность кидать эксепшн ElementNotFound по таймауту.

**Comment by MihaylovNikitos** [comment]
Это видел) Но проблема в том, что в старой версии ловится, а вот в новой нет. В коде меняется только ContestoDriver на ContestoWebDriver.

Спс, за то что помогаешь.) Но извини код показат не могу, да и вся цепочка действий, будет длиная.

**Comment by nwlunatic** [comment]
@rseek прав. В этом месте мы сломали обратную совместимость, чтобы не отбирать возможность использовать стандартные средства selenium не monkey patch'а их.

поэтому теперь существует отдельный способ поиска элементов: 
http://contesto.readthedocs.org/en/master/finder.html#module-contesto

можно вручную сделать такой же monkey patch где-то в инициализации:
```python
from contesto import find_element, find_elements, ContestoWebDriver, ContestoWebElement
ContestoWebDriver.find_element = find_element
ContestoWebDriver.find_elements = find_elements
ContestoWebElement.find_element = find_element
ContestoWebElement.find_elements = find_elements
```
